### PR TITLE
add the word chop

### PR DESCRIPTION
**Pull request by downvoid**

### CODE REVIEW

**Comment by Zamiell** [comment]
you have to update level 11 and the beginners guide too, right?
also, it is more gramatically correct to say "their chop card", not just "chop".

**Comment by downvoid** [comment]
wait, level 11? what do I have to change there?

**Comment by downvoid** [comment]
I've fixed the other stuff, but I don't see anything on level 11 related to this

**Comment by Zamiell** [comment]
level 8 i meant, not level 11

**Comment by downvoid** [comment]
ah there we go

**Comment by Zamiell** [comment]
the grammar is still weird, i would word it like this:

"the period of time before any player has discarded their chop card"

**Comment by downvoid** [comment]
I just copied exactly what you put

**Comment by Zamiell** [comment]
you only updated 1 page though, all 3 pages should have the same wording.

**Comment by downvoid** [comment]
is this what you wanted

**Comment by Zamiell** [comment]
yep

**Pull request merged**
