### PR TITLE
Move clarity principle to level 10

### PR DESCRIPTION
**Pull request by downvoid**

### CODE REVIEW

**Comment by Zamiell** [comment]
i thoguht we wanted to move it to level 5 (?)

**Comment by downvoid** [comment]
you said level 5 is already too long, so level 10 was the next level that fits well

**Comment by downvoid** [comment]
oh wait, I misread that

**Comment by Zamiell** [comment]
level 6, not level 5

**Comment by downvoid** [comment]
there, it's now at level 6

**Pull request merged**
