### PR TITLE
Patch 9

### PR DESCRIPTION
**Pull request by Gingy120-github**
Fixes a grammar error in level 14.

Adds a new section to level 18 to clarify the interaction between trash moves and elimination. Added some new images too.

### CODE REVIEW

**Comment by Gingy120-github** [comment]
Sorry, the many commits that I made while editing the same file over and over again seem to have stayed and not collapsed into a single commit. Not sure how to condense it all, unfortunately.

**Comment by Gingy120-github** [comment]
opening new pull request with fixes to tests

**Comment by Zamiell** [comment]
it is not required that PRs be a single commit, as we will squash them all when the PR is merged.
thus, feel free to make a PR with as many commits as you like, it is irrelevant.

**Comment by Zamiell** [comment]
however, a PR should do 1 thing, so if you are fixing a grammar mistake, do that in a separate PR from adding a new section.

**Pull request closed without merging**
