### PR TITLE
Move 5 stall's to level 2

### LINKED ISSUE #762: Move 5 stall’s to Level 2 (not level 1)
For newcoming players I think this is one less thing to worry about at first, and the *need* to 5-stall in No Variant at Level 1 is not that drastic.

### PR DESCRIPTION
**Pull request by vEnhance**
Closes #762

### CODE REVIEW

**Comment by Zamiell** [comment]
there should be no mention of a 5 stall in level 1.
move the questions specifically relating to a 5 stall to level 2

**Comment by vEnhance** [comment]
>  move the questions specifically relating to a 5 stall to level 2, if any

Do any of the later levels actually have questions right now? (Not sure where to put them.)

**Comment by Zamiell** [comment]
> Do any of the later levels actually have questions right now? (Not sure where to put them.)

no
in this case, you will have to design new sections accordingly

**Comment by Zamiell** [comment]
in the question where you deleted `The **only** legal action that Alice can perform is to clue number 5 to Donald as a *5 Stall* on the purple 5.`, we should regenerate that question in a slightly different form in the level 2 section

**Comment by vEnhance** [comment]
Alright, shuffled around.

**Comment by Zamiell** [comment]
fails lint

**Comment by Zamiell** [comment]
thanks

**Pull request merged**
