### PR TITLE
Update omni.mdx

### PR DESCRIPTION
**Pull request by vEnhance**
crosslink pink conventions

### CODE REVIEW

**Comment by Zamiell** [comment]
thx.
do you also want to investigate why ci is failing?

**Comment by vEnhance** [comment]
Looks like https://stackoverflow.com/questions/76708329/docker-compose-no-longer-building-image-attributeerror-cython-sources

upgrading pyyaml should fix it, let me try

**Comment by Zamiell** [comment]
yeah might as well upgrade all the deps to latest while you are at it

**Comment by Zamiell** [comment]
thanks!

**Pull request merged**
