### PR TITLE
Add udd to level 16

### PR DESCRIPTION
**Pull request by unsoftcapped3**

### CODE REVIEW

**Comment by Zamiell** [comment]
its intentionally not in level 16.
what is the point of this pr?

**Comment by unsoftcapped3** [comment]
many people have requested it to be part of level 16. Almost all level 16 players know it. This is to formalize udd being turned on in level 16 games.

**Comment by unsoftcapped3** [comment]
If you make a poll I think most people would agree this should be in level 16

**Comment by Zamiell** [comment]
if you want to do a poll, the correct way is to open a github issue, can you open an issue?

**Pull request closed without merging**
