### PR TITLE
Clarify Priority with Known+Unknown cards

### PR DESCRIPTION
**Pull request by english5040**

### CODE REVIEW

**Comment by Zamiell** [comment]
I'll have ADrone take a look at this PR, since he was in charge of the last priority change/clarification

**Comment by EhDrone** [comment]
I might be missing something - but you updated it to describe the opposite scenario of what the section is trying to explain. Sorry if I am reading it wrong -- but the point of that section is to let people know that playing an Unknown card instead of the known card, but you updated the section to describe playing a known card over an unknown card.

**Comment by english5040** [comment]
There are two cases the original was trying to describe: when does playing an unknown over a known cause a PF and when does playing known over unknown cause a PF. In the first case that generally does nothing, and the second case is the important one to discuss, wherein the orig. doc was confusingly phrased

**Comment by english5040** [comment]
The orig. doc was trying to say that the known has to have lower priority than all unknown superpositions but said it badly and reversed it

**Comment by english5040** [comment]
additionally, according to the priority table, the original examples were invalid, so I changed them to reflect the current priority table

**Comment by english5040** [comment]
hm, I can rephrase some of the wording, I think

**Comment by english5040** [comment]
there we go, now it's all about whether the known has strictly lower priority than the unknown identities

**Comment by english5040** [comment]
This PR is now obsolete after a discussion with ADrone; it reflected a common interpretation of the priority table which was not the intended meaning

**Pull request closed without merging**
