### PR TITLE
Double Ignition Edits, Poke Ignition/Ejection, and Replay Ignition/Ejection

### PR DESCRIPTION
**Pull request by Jayhui-q**
Renaming Double Ignition to Trash Double Ignition. 
Adding Replay and Poke Double Ignition/Ejection.

### CODE REVIEW

**Comment by Jayhui-q** [comment]
Might need to look over the hyperlinks I put in. (References to the replay/poke double ignitions in the ejections section, and the reference to stalling in the replay ejection section.) 

I'm not 100% sure how the file/folder interaction works with the various .md files.

**Comment by Zamiell** [comment]
the links have to be in the form of `level_19.md#poop`

**Comment by Jayhui-q** [comment]
Sweet, thanks! Wasn't sure as level 19 seemed to be a folder with several .md files in it. 
Just made the changes

**Comment by Zamiell** [comment]
looks good thanks, ill make some minor edits later

**Comment by Jayhui-q** [comment]
As a small note: I didn't add in the trash ejection because I believe the trash ejection is synonymous with the BCME (with a trash chop move). The trash ejection definition is more restrictive than BCME as well.

**Comment by Zamiell** [comment]
its not synonymous with BCME in the case where you clue e.g. four 1's

**Comment by Jayhui-q** [comment]
Ah, you're right. Good catch!

**Pull request merged**
