### PR TITLE
Update level-2.mdx

### PR DESCRIPTION
**Pull request by argothiel**

### CODE REVIEW

**Comment by Zamiell** [comment]
looks like your edit has an error in it

**Comment by argothiel** [comment]
What error?

**Comment by Zamiell** [comment]
i mean just look at it, you are combining a parenthetical with a half-sentence

**Comment by argothiel** [comment]
Thanks, I've updated the fix. Next time, please try and be more specific with your feedback. If I missed the error once, your "just look at it" isn't very helpful.

**Comment by Zamiell** [comment]
looks good thanks

**Pull request merged**
