### PR TITLE
Add a line about hyphen-ated group features

### PR DESCRIPTION
**Pull request by jack67889**
Beginners are always surprised when you tell them about this.

### CODE REVIEW

**Comment by Zamiell** [comment]
DDA isn't a level 1 convention so i dont think this information is appropriate for level 1

**Comment by jack67889** [comment]
Play order of 1s and sarcastic discards are level 3. This seemed to be the most appropriate section to me; I searched for 'website features' to find it myself. Or would you suggest adding an extra section in level 3?

**Comment by Zamiell** [comment]
the main point of the hyphenated checkbox is for DDA alerting, so maybe a new section below where DDA is introduced

**Comment by jack67889** [comment]
Okay, although I would think the ocm sound is most helpful when you still forget to pay attention to it.

**Comment by Zamiell** [comment]
given that this pr hasn't been updated, i will close it

**Pull request closed without merging**
