### PR TITLE
Add interaction between Occam's Razor and Bob's Truth Principle

### PR DESCRIPTION
**Pull request by Lel0uch-H**

### CODE REVIEW

**Comment by Lel0uch-H** [comment]
This has been the focus of many disagreements during reviews. Adding this here would be helpful I think.

**Comment by Zamiell** [comment]
why is it at level 14 instead of e.g. after the Occams Razor section

**Comment by Lel0uch-H** [comment]
Because before level 14, Bob cannot be in such a dilemma. Correct me if I am wrong.

**Comment by Zamiell** [comment]
oh i see, because it has to do with double bluffs

**Comment by Zamiell** [comment]
ok thanks, i did a few edits

**Pull request merged**
