### PR TITLE
Update pink.mdx

### PR DESCRIPTION
**Pull request by newduke**
Clarify pink trash moves

### CODE REVIEW

**Comment by Zamiell** [comment]
Can you make it pass ci

**Comment by Zamiell** [comment]
still doesn't pass ci

**Comment by newduke** [comment]
It passes CI

**Comment by Zamiell** [comment]
i dont understand the clarification. is this a brand new convention?

**Comment by newduke** [comment]
It changes nothing. But it was confusing before as to what happens in these situations. Notably, players were confused about bluffs in pink because they can be confused with utc.

**Comment by Zamiell** [comment]
it looks like it changes the trash bluff rules.
what you clarified isn't how we play.
trash bluffs !== UTD

**Comment by Zamiell** [comment]
have you read this section? https://hanabi.github.io/docs/variant-specific/pink/#trash-finesses--trash-bluffs-in-pink

**Comment by newduke** [comment]
Hrm fair. But what if all trash? Should still be utc no?

**Comment by Zamiell** [comment]
yes, it would be UTC, but does that need a clarification? it just works the same as No Variant, i dont think there needs to be a separate section to clarify just that (?)

**Comment by Zamiell** [comment]
can you update the pr?

**Comment by Zamiell** [comment]
thanks

**Comment by NZadeh** [comment]
for what it's worth, this is definitely not how most would people play the clue (though people's interpretations may have conflicted with some of the previous language).

for example, a 1 clue touching i1, r1, b1 that is intending to get the final 1 to play from finesse.... is now supposed to be a charm? I don't think that's how anyone will play.

The perception is likely to be that the doc just looks _more_ wrong now, not less.

I suspect a happy compromise would be something like: a player is promised all trash, unless "fixed" to be shown prink cards. But I haven't thought through the exact convention.

**Comment by NZadeh** [comment]
It's also worth mentioning that this is lvl 21 in pink, but a charm isn't introduced until level 24...

**Comment by Zamiell** [comment]
> It's also worth mentioning that this is lvl 21 in pink, but a charm isn't introduced until level 24

can you submit a pr to add the standard boilerplate "if you are level 24, then" part?

**Comment by Zamiell** [comment]
> for what it's worth, this is definitely not how most would people play the clue

then someone should start a github thread to change the conventions.
i'm not just going to arbitrarily change the doc because some of the new players are going rogue and playing differently

**Comment by NZadeh** [comment]
haha I think it's more that the old players are going rogue. new players have little reason to.

**Comment by NZadeh** [comment]
> > It's also worth mentioning that this is lvl 21 in pink, but a charm isn't introduced until level 24
> 
> can you submit a pr to add the standard boilerplate "if you are level 24, then" part?

what does the move mean before level 24? bad touch trash bluff/finesse?

**Pull request merged**
