### PR TITLE
Adding 5 number ejection to sections where it is missed.

### PR DESCRIPTION
**Pull request by Stuurrm**
As a side note the example in docs/examples/5-number-discharge.mdx no longer describes a discharge but an ejection. I do not happen to have an actual example of a 5 number discharge on hand.

### CODE REVIEW

**Comment by Stuurrm** [comment]
It has been fixed

**Comment by Zamiell** [comment]
> As a side note the example in docs/examples/5-number-discharge.mdx no longer describes a discharge but an ejection. 

can you change the example so that it properly describes the correct thing?
otherwise delete the example

**Comment by Stuurrm** [comment]
As said I do not actually have an example to give so deleting it.

**Comment by Zamiell** [comment]
Excellent, thank you

**Pull request merged**
