### PR TITLE
Try to clarify what a Shout Discard is

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by Zamiell** [comment]
can you put blaze discard stuff in a separate pr?

**Comment by DarthGandalf** [comment]
Done.

To clarify the source of confusion: "This situation" refers to the situation in the previous sentence just before the word "this". But the latest situation in that sentence is Scream Discard. So it instead needs to refer to the situation before the previous one, which was still talking about discarding trash. The new text avoids this issue, and explicitly says what this new term means

**Comment by Zamiell** [comment]
see my edits

**Comment by Zamiell** [comment]
if that is okay with you then ill accept the pr

**Comment by DarthGandalf** [comment]
> if that is okay with you then ill accept the pr

Such question implies that you'd wait for me to tell you whether it's okay. But LGTM

**Pull request merged**
