### PR TITLE
Change outcome of ex 2 without relying on bluff targets

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by Zamiell** [comment]
why does this pr have two separate changes

**Comment by DarthGandalf** [comment]
Because it's easier this way, less merge conflicts with myself

**Comment by Zamiell** [comment]
can you please put 1 change in 1 pr, that way it is easier to revert if needed

**Comment by DarthGandalf** [comment]
Merge them via merge or rebase, without squashing them into one commit. Then it's easy to revert

**Pull request merged**
