### PR TITLE
example pictures added

### PR DESCRIPTION
**Pull request by DrAnax**

### CODE REVIEW

**Comment by Zamiell** [comment]
> This branch has conflicts that must be resolved

**Comment by DrAnax** [comment]
Don't know what to do git-wise. Found the error in line 115. Do I close and resubmit?

**Comment by DrAnax** [comment]
I made the change from 'an clue' to 'a clue' but I don't know how to deal with it via git/github.

**Comment by Zamiell** [comment]
if you made the change, then push the change with a commit to your branch, and github will re-run CI

**Comment by DrAnax** [comment]
When it's ok, please have a look at the picture of the last example. Are Cathy's el notes correct? (I excluded the chop)

**Comment by Zamiell** [comment]
ill go through all the images later

**Pull request merged**
