### PR TITLE
Fix CI in #1008 (dupe tech)

### PR DESCRIPTION
**Pull request by vEnhance**
Originally by @pianoblook 

Also merged main in so there shouldn't be conflicts either

Closes #1008

### CODE REVIEW

**Comment by vEnhance** [comment]
Now that I'm looking more closely (at things that aren't just CI) it looks like there are some links that are going to need fixing too. 

Wish I had written that Python script in https://github.com/hanabi/hanabi.github.io/issues/817#issuecomment-1219210517 now :')

**Comment by vEnhance** [comment]
> Wish I had written that Python script in [#817 (comment)](https://github.com/hanabi/hanabi.github.io/issues/817#issuecomment-1219210517) now :')

And now the script is done, there's a `move-levels.sh` that does what you would expect it to.

So all the level numbers should be up-to-date now. I hope. :pray: 

(Closes #947)

**Comment by Zamiell** [comment]
should i just close piano's PR then?

**Comment by vEnhance** [comment]
> should i just close piano's PR then?

Yeah, I think everything piano sent in should be in this one.

**Comment by Zamiell** [comment]
ok

**Comment by Zamiell** [comment]
thanks piano/evan

**Pull request merged**
