### PR TITLE
Fix interaction with 5 clues link in level 17

### PR DESCRIPTION
**Pull request by timotree3**
The playful ignition used to be in Miscellaneous but now it's not.

### CODE REVIEW

**Comment by Zamiell** [comment]
i already fixed this on master i think

**Comment by timotree3** [comment]
No you didn't

**Comment by timotree3** [comment]
The link you replaced it with is useless. There is no "Interaction with 5 rank clues" section on the miscellaneous page

**Comment by Zamiell** [comment]
can you link the section in question?

**Comment by timotree3** [comment]
current link in master https://hanabi.github.io/docs/extras/miscellaneous/#interaction-with-5-rank-clues

correct link https://hanabi.github.io/docs/level-20#interaction-with-5-rank-clues

if you look at the diff of the PR, that is what it literally shows you

**Comment by Zamiell** [comment]
no, i meant link the place where it is bugged in master

**Comment by Zamiell** [comment]
again, i dont see any issues in master

anyways, i think the new linter isn't working

**Comment by timotree3** [comment]
Okay yep it is fixed now.

**Pull request closed without merging**
