### PR TITLE
Critical Fours

### LINKED ISSUE #1170: Critical fours
Given there's no page dedicated to critical fours yet, we could look at creating one.

During pick-up games with Newsun, Wshull, Tailz, and Kernel, our main agreements were
- no _critical color bluffs_ on fours (analogous to "no critical color bluffs on fives")
  - allowing _critical color bluffs_ on fours would let color be a single bluff, while rank would be a double bluff or charm. Better to allow them then?
- fours to be saved with rank instead of color (analogous to "save 5s with rank")
  - Newsun suggested _Florrat saves_ as an exception

### PR DESCRIPTION
**Pull request by gw12346**
Closes #1170.

Potential future experiments could involve turning off 3 bluffs and/or critical color bluffs.

### CODE REVIEW

**Comment by Zamiell** [comment]
can you make it pass ci?

**Comment by Zamiell** [comment]
this PR is messed up, it includes edits from the other PRs

**Comment by Zamiell** [comment]
can you remove all the edits that don't have to do with critical 4s?

**Comment by vEnhance** [comment]
So I removed the offending commits that touched special-fives.mdx and merged against main, but it looks like Zamiell was faster and already added in the relevant change into main as 5ea75d522 and b0cb7f5f4. That means there's nothing left in this pull request to actually merge, I think?

**Comment by gw12346** [comment]
Ah, that's why there's nothing to change in this pull request. Thank you Evan and James for your help!

**Comment by Zamiell** [comment]
yeah i added it for now, in the future remember to put each pr on a separate branch so that way your prs dont meld together like frankenstein

**Pull request closed without merging**
