### PR TITLE
Update muddy-rainbow-cocoa-rainbow.md

### PR DESCRIPTION
**Pull request by newduke**
Clarify difference in positional between null and muddy

### CODE REVIEW

**Comment by Zamiell** [comment]
in null dark suits are skipped, and in muddy dark suits are skipped

right?

**Comment by iamwhoiamhahaha** [comment]
https://discord.com/channels/140016142600241152/456214043351580674/974955915780423790

**Comment by newduke** [comment]
I am pretty sure I've seen this discussion pop up here and there and the verdict is always we don't skip dark for mud clues.

**Comment by Zamiell** [comment]
if you want to change the conventions, then you are supposed to open a new issue, not a pull request.
afaik currently dark suits are skipped.

**Comment by Zamiell** [comment]
branch has conflicts, can you fix

**Review by newduke — COMMENTED** [review]
Merged

**Pull request merged**
