### PR TITLE
Junk 1s D&C

### PR DESCRIPTION
**Pull request by pianoblook**

### CODE REVIEW

**Comment by Zamiell** [comment]
fails the linter, make sure you run `./lint.sh` on your fork before submitting a pr

**Comment by pianoblook** [comment]
looks like it just doesn't recognize the name avanderwalde

**Comment by Zamiell** [comment]
right click her name and select "add to workplace dictionaries"

**Comment by pianoblook** [comment]
sigh, I don't see any options like that :( Maybe that's the kind of thing you need special software to do?

**Comment by Zamiell** [comment]
are you using vscode?

**Comment by pianoblook** [comment]
I'm using Chrome 👀 

also I (hopefully?) just folded in the Fake Pink line as well.

**Comment by Zamiell** [comment]
can you use vscode instead? follow the instructions here: https://github.com/hanabi/hanabi.github.io/blob/main/README.md#how-to-submit-a-pull-request-complicated

**Pull request merged**
