### PR TITLE
No loaded 5s ever.

### PR DESCRIPTION
**Pull request by unsoftcapped3**

### CODE REVIEW

**Comment by Zamiell** [comment]
please read https://github.com/hanabi/hanabi.github.io/blob/main/misc/convention-changes.md, which goes over how we change conventions

**Comment by unsoftcapped3** [comment]
You literally just merged his change without getting feedback from anyone else.

**Comment by unsoftcapped3** [comment]
did a single person approve it?

**Comment by Zamiell** [comment]
afaik this was just a clarification of an existing convention, not a new convention. from what im reading of ALP, it should apply equally to white 2 and white 5, correct me if i am wrong

**Comment by unsoftcapped3** [comment]
It does not apply to white 5. Have you ever seen a game where anyone played with loaded 5s? I haven't. I play with a lot of people in H group and no one plays with loaded 5s when doing white.

**Comment by unsoftcapped3** [comment]
this is not "just a clarification of an existing convention". It introduces a new convention (all 5s are loaded) that we were not playing with before. This is a new convention and was added without any consensus.

**Comment by Zamiell** [comment]
right now i'm going off what the doc says, can we restrict the convention to that please?

**Comment by yagamiblack** [comment]
The doc for White explicitly mentioned rank clues with 2, 3, and 4 before the aforementioned pull request, therefore adding white 5 *IS* a convention change, and one that was not approved without any feedback.

**Comment by Zamiell** [comment]
afaik that line is just a reiteration of what ALP means, right?

**Comment by unsoftcapped3** [comment]
The line "Since it can be hard to get white cards on chop to play, the Always Loaded Principle applies to save clues given with number 2, number 3, and number 4" is not a reiteration of what ALP means. It is a specific added convention to the white variant.

**Comment by Egroegw** [comment]
I suggest then that we clarify the ALP and, if necessary, change the Gray convention page to stop implying that the ALP applies to 5s.

**Comment by unsoftcapped3** [comment]
sure I can do that

**Comment by yagamiblack** [comment]
Also do note that as the majority of H Group players do not play with loaded number 5 clues in White, the previous pull request will only cause confusion when newer players reading White conventions play with more experienced players, hence the need for more community discussion.

**Comment by jack67889** [comment]
Having the convention apply to 5s is at least not in the spirit of the reason to introduce the convention [in the first place](https://github.com/hanabi/hanabi.github.io/issues/730). But I agree it's very unclear and it has been raised multiple times by several people since the introduction, but I've never seen any clarification. I've never understood what the intention of the convention is.

Problem is also that the example suggests it only applies to cards that could be currently playable white cards (like the convention that preceded it), but that is also left unclear. In a [discussion on Discord](https://discord.com/channels/140016142600241152/456214043351580674/928537046849576960) it was suggested that the intention is indeed to only differentiate between play/save, like the example, which makes the wording of the actual convention way too broad imo. If that's the intention you're probably better off to restrict it to only possible playable white cards (with or without self finesses?). A stricter interpretation would also leave open the possibility for rank self-finesses instead of (any) saves. While that convention was deleted right before ALP was introduced, so that also seems unintended to me.

**Comment by Zamiell** [comment]
thanks jack for the summary, i'll open a new issue

**Pull request closed without merging**
