### PR TITLE
Generate example images programmatically.

### PR DESCRIPTION
**Pull request by DarthGandalf**
I'll leave a better integration of this into the build system to you.

### CODE REVIEW

**Comment by Zamiell** [comment]
wtf, rebase your branch on master

**Comment by Zamiell** [comment]
oh, nm it is

**Comment by Zamiell** [comment]
ok lets try it out

**Comment by Zamiell** [comment]
im working on generating the svg cards, it isn't easy

**Comment by Zamiell** [comment]
the appearance of cards has been updated since the SVG commit that i found, so i have to backwards integrate it

**Comment by Zamiell** [comment]
why did you create elements for each image instead of just doing `Poop` ?

**Comment by DarthGandalf** [comment]
> why did you create elements for each image instead of just doing Poop ? e.g. the markdown way to show images

That's what I tried at the beginning. But then `<image>` with the "sprites" of cards weren't showing, because `` is supposed to be self-contained. The external images were silently not loaded from the website. When embedding `<svg>` directly in the resulting HTML, it wasn't a problem anymore.

**Pull request merged**
